### ISSUE TITLE
Crashed after updating to 6.0.0

### ISSUE THREAD

**Issue by v-divya110** [mcollina/aedes-persistence-level#18]
```/usr/local/lib/node_modules/aedes-persistence-level/node_modules/msgpack-lite/lib/read-core.js:24
    if (!func) throw new Error("Invalid type: " + (type ? ("0x" + type.toString(16)) : type));
               ^

Error: Invalid type: 0x�
    at Codec.decode (/usr/local/lib/node_modules/aedes-persistence-level/node_modules/msgpack-lite/lib/read-core.js:24:22)
    at DecodeBuffer.fetch (/usr/local/lib/node_modules/aedes-persistence-level/node_modules/msgpack-lite/lib/decode-buffer.js:26:21)
    at DecodeBuffer.read (/usr/local/lib/node_modules/aedes-persistence-level/node_modules/msgpack-lite/lib/flex-buffer.js:166:28)
    at Object.decode (/usr/local/lib/node_modules/aedes-persistence-level/node_modules/msgpack-lite/lib/decode.js:10:18)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/aedes-persistence-level/persistence.js:41:25)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/aedes-persistence-level/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/aedes-persistence-level/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/local/lib/node_modules/aedes-persistence-level/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/aedes-persistence-level/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/aedes-persistence-level/node_modules/readable-stream/lib/_stream_writable.js:334:11)
```

**Comment by mcollina** [comment]
Can you please provide a way to reproduce or a PR to fix? I’ve updated
level that changed the way it handles encoding.
Il giorno ven 20 lug 2018 alle 14:23 Divya Venkataramani <
notifications@github.com> ha scritto:

**Comment by v-divya110** [comment]
If you undo the commit in test.js by replacing 
```
var levelup = require('levelup')
var memdown = require('memdown')
function memdb () {
  return levelup(memdown())
}
```
with `var memdb = require('memdb')`, you'll get the exact same error

**Comment by mcollina** [comment]
Memdb is using an old version of level. You should update to the latest version

**Comment by v-divya110** [comment]
Okay, agreed. Its the way I initialise my database which led to the problem when I updated level. I'll close this now.
